### ISSUE TITLE
iceworks add error 当前物料模板不存在 page 类型的物料

### ISSUE THREAD

**Issue by xmsz** [appworks-lab/pack#699]
```
➜  ice-materials iceworks init
iceworks CLI: 3.4.2
? Please select a type material collection(component&scaffold&block&page)
? Please select a template Rax + TypeScript
download template tarball https://registry.npm.taobao.org/@icedesign/template-rax/download/@icedesign/template-rax-0.4.3.tgz
✔ download npm tarball successfully.
? npm scope (eg: @ice) @coolban
? materials name ice-materials
? description ice物料库

      Initialize material successfully!
      Inside that directory, you can run several commands:

        Install dependencies
          npm install

        Starts the block development server.
          cd blocks/ExampleBlock
          npm install
          npm start

        Generate materials json.
          npm run generate

        You can upload the JSON file to a static web server and put the URL at iceworks settings panel.
        You will see your materials in iceworks

        We suggest that you can sync the materials json to fusion.design by run:
          npm run sync

      Happy hacking!

```

```
➜  ice-materials iceworks add page
iceworks CLI: 3.4.2
download template tarball https://registry.npm.taobao.org/@icedesign/template-rax/download/@icedesign/template-rax-0.4.3.tgz
✔ download npm tarball successfully.
? page name DefaultPage
? title Default Page
? version 1.0.0
? description 默认页面模板，带有BeforeRouter组件 + scss基础样式
? category Basic
ERR! iceworks add error 当前物料模板不存在 page 类型的物料
Error: 当前物料模板不存在 page 类型的物料
    at Object.<anonymous> (/usr/local/lib/node_modules/iceworks/node_modules/@iceworks/generate-material/lib/index.js:67:31)
    at step (/usr/local/lib/node_modules/iceworks/node_modules/@iceworks/generate-material/lib/index.js:44:23)
    at Object.next (/usr/local/lib/node_modules/iceworks/node_modules/@iceworks/generate-material/lib/index.js:25:53)
    at /usr/local/lib/node_modules/iceworks/node_modules/@iceworks/generate-material/lib/index.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/iceworks/node_modules/@iceworks/generate-material/lib/index.js:15:12)
    at Object.generateMaterial (/usr/local/lib/node_modules/iceworks/node_modules/@iceworks/generate-material/lib/index.js:60:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/iceworks/lib/command/init/addSingleMaterial.js:99:62)
    at step (/usr/local/lib/node_modules/iceworks/lib/command/init/addSingleMaterial.js:33:23)
    at Object.next (/usr/local/lib/node_modules/iceworks/lib/command/init/addSingleMaterial.js:14:53)
    at fulfilled (/usr/local/lib/node_modules/iceworks/lib/command/init/addSingleMaterial.js:5:58)
```

**Comment by alvinhui** [comment]
https://github.com/ice-lab/material-templates/tree/master/packages/template-rax/template 

少了页面级的模板，可以参考

https://github.com/ice-lab/material-templates/tree/master/packages/template-react/template/page

**Comment by xmsz** [comment]
> https://github.com/ice-lab/material-templates/tree/master/packages/template-rax/template
> 
> 少了页面级的模板，可以参考
> 
> https://github.com/ice-lab/material-templates/tree/master/packages/template-react/template/page

https://github.com/ice-lab/material-templates/tree/master/packages/template-rax/template 的少了page的示例

**Comment by alvinhui** [comment]
这个功能使用的场景比较少，工作量比较大，经过我们的讨论，决定下线掉。
